#EDC Configuration
#Mon May 11 23:40:24 PDT 2026
Browser=Chrome
CreateDashboard=No
CreateExperienceBuilderApp=No
CreateFeatureLayer=No
CreateMap=No
CreateMember=No
CreateSceneLayer=No
CreateStoryMap=No
CreateTileLayer=No
CreateWebAppBuilder=No
Federated1=Yes
Federated10=Yes
Federated2=Yes
Federated3=Yes
Federated4=Yes
Federated5=Yes
Federated6=Yes
Federated7=Yes
Federated8=Yes
Federated9=Yes
Kubernetes=No
LoginManager=Yes
LoginPortal=No
LoginServer=No
PortalPassword=
PortalUrl=
PortalUserName=
RunAllTest=No
ServerAdminPassword1=
ServerAdminPassword10=
ServerAdminPassword2=
ServerAdminPassword3=
ServerAdminPassword4=
ServerAdminPassword5=
ServerAdminPassword6=
ServerAdminPassword7=
ServerAdminPassword8=
ServerAdminPassword9=
ServerAdminUsername1=
ServerAdminUsername10=
ServerAdminUsername2=
ServerAdminUsername3=
ServerAdminUsername4=
ServerAdminUsername5=
ServerAdminUsername6=
ServerAdminUsername7=
ServerAdminUsername8=
ServerAdminUsername9=
ServerRole1=Hosting Server
ServerRole10=
ServerRole2=
ServerRole3=
ServerRole4=
ServerRole5=
ServerRole6=
ServerRole7=
ServerRole8=
ServerRole9=
ServerUrl1=
ServerUrl10=
ServerUrl2=
ServerUrl3=
ServerUrl4=
ServerUrl5=
ServerUrl6=
ServerUrl7=
ServerUrl8=
ServerUrl9=
ValidateDataStores=No
ValidateOrganization=No
ValidateServerRole=No
